export default function NewsPage() {
  return (
    <div className="container my-4">
      <section className="about-document-assembly-line mt-4">
        <h1>Guided Interviews Terms of Use and Data Privacy Policy</h1>
        <div>
          <p>
            Suffolk University Law School's Legal Innovation and Technology Lab
            ("the LIT Lab") is a legal technology consulting shop housed within
            the Suffolk University Law School ("the Law School"), a non-profit
            educational institution based in the Greater Boston Area.
          </p>
          <p>
            The website ("massacess.suffolklitlab.org" and
            "apps.suffolklitlab.org") and the guided interviews available there
            are provided as a free service for those wishing to file forms with
            the Massachusetts Trial Courts. By using the service, you accept and
            agree to the terms of use and privacy policy set forth below.
          </p>

          <h2>Terms Of Use and Data Privacy Policy</h2>
          <h4>Important disclaimers</h4>
          <ul>
            <li>
              This website does not constitute legal advice. You should consult
              a lawyer for legal advice.
            </li>

            <li>
              We use our best efforts to prepare the forms on this site and to
              keep them up to date. Law changes or court or local variations may
              make any forms generated by this site unenforceable.
            </li>

            <li>
              This website is offered completely without warranty, including an
              implied warranty of fitness. The LIT Lab disclaims all liability
              for your use of information on this website or your reliance on
              the forms created by a guided interview.
            </li>

            <li>
              You agree to indemnify and hold harmless the LIT Lab and the Law
              School for all claims arising out of your use of these guided
              interviews or the information that they give you.
            </li>

            <li>
              the LIT Lab does not offer technical support for the interviews
              provided on this website.
            </li>

            <li>
              Information you enter may not be protected by attorney-client
              privilege or attorney work product doctrine.
            </li>

            <li>
              Do not use this system to conduct unauthorized practice of law. If
              you do, you may face civil or criminal liability.
            </li>
          </ul>

          <h4>How you are allowed to use this website</h4>

          <ul>
            <li>You must be over the age of 13 to use this website.</li>
            <li>Commercial use is not allowed.</li>
            <li>You may not re-sell access to our service.</li>
            <li>
              If you are representing a client, even for a fee, you may
              occasionally use this site during the course of your
              representation as long as you disclose that it is available for
              free from the LIT Lab. If you intend to use it regularly, you
              should contact the LIT Lab for a special arrangement.
            </li>
            <li>
              Excessive use, abuse, or any use that interferes with the use of
              the system by others is not allowed.
            </li>
          </ul>

          <h4>What information we collect from you</h4>

          <ul>
            <li>
              Information that you type in the guided interview, which may
              include private information such as your name, address, and
              identification numbers.
            </li>

            <li>
              Information sent automatically by your web browser, which includes
              information about your information service provider, your location
              and third-party analytics such as Google Analytics. This
              information is used to protect the system from unauthorized use
              and to understand the demographics of the users of our site and to
              improve the forms and interviews contained on this site.
            </li>

            <li>
              Information from your web browser may be stored in computer logs
              for up to 180 days and reviewed to maintain the security of our
              system. Anonymous analytics may be stored indefinitely.
            </li>

            <li>
              We use cookies to allow you to return to the site and finish an
              interview that is in progress. At any time you may delete your
              saved answers stored on our servers by accessing{' '}
              <a href="https://apps.suffolklitlab.org/user/sign-in?next=https://apps.suffolklitlab.org/interviews">
                My Forms
              </a>
              .
            </li>
          </ul>

          <h4>What Information We Share With Others</h4>

          <ul>
            <li>
              {' '}
              We deliver the contents of your completed forms to the MA Trial
              Court.
            </li>

            <li> We will never sell your data.</li>

            <li>Third-party analytics to improve our website.</li>

            <li>
              We may use a third party service to store saved answers from
              completed interviews. We will delete your information upon written
              request.
            </li>

            <li>
              We may use anonymized data that you provide for research purposes
              in order to understand how to better provide legal services to the
              citizens of Massachusetts. Anonymous information may be shared
              with academic researchers to help with this goal. This information
              will never include your private, identifying details.
            </li>
          </ul>

          <h4>How we protect your information</h4>

          <ul>
            <li>
              All information sent to our servers and sent back to you is
              encrypted with standard HTTPS SSL encryption to protect it from
              other users on your network or in between your computer and the
              LIT Lab.
            </li>

            <li>
              We make use of software controls, firewalls, and continuous
              monitoring to protect your information and to maintain the
              security of the website.
            </li>

            <li>
              Access to your responses is limited to logged-in and authorized
              employees of the LIT Lab, only when necessary to make improvements
              to the system or at your request.
            </li>

            <li>
              However: if you share a link to your interview, any person with
              that link may have access to the responses you gave in that
              interview.
            </li>
          </ul>

          <h3>Our Response Times</h3>
          <ul>
            <li>
              We respond to general data inquiries from users within 30 days.
            </li>
            <li>
              We will inform users of any data breach involving their interview
              data within 72 hours of discovery.
            </li>
          </ul>

          <h3>Amendments</h3>

          <p>
            The LIT Lab may modify, alter, or update these Terms of Use at any
            time with or without notice. Please review the link on a regular
            basis for any such changes.
          </p>
          <p>
            If you continue to use our website following a change to these Terms
            of Use, you will be deemed to have accepted the changes.
          </p>
          <h2>General</h2>

          <p>
            If any term or condition set out in this Terms of Use is held to be
            invalid, unenforceable or illegal for any reason, the remaining
            terms and conditions will continue in full force.
          </p>
          <p>
            These Terms of Use are governed by the laws of the Commonwealth of
            Massachusetts and deemed to be entered into by you and the LIT Lab.
          </p>

          <p>
            Please send any questions or comments about this Terms of Use and
            Privacy Policy to Suffolk LIT Lab, 120 Tremont St, Boston MA.
          </p>
        </div>
      </section>
    </div>
  );
}
